.TH "bug" 3 "Mercredi Février 12 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Liste des bogues 
.IP "\fBMembre \fBmatrice_chargement\fP (FILE *fichier)\fP" 1c
si dans un fichier la taille est > 9, il y a un problème pour récupérer le nombre de ligne, et de colonnes\&. Il faut changer fgetc par autre chose\&. 
.PP

