.TH "include/chaines.h" 3 "Jeudi Février 20 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/chaines.h \- 
.PP
\fBEnsemble\fP des chaines\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ensemble\&.h>\fP
.br
\fC#include <chaine\&.h>\fP
.br

.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef \fBEnsemble\fP \fBChaines\fP"
.br
.RI "\fIChaines est une ensemble de chaine (alias d'un ensemble) \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBchaines_appartient_chaine\fP (\fBChaines\fP chaines, \fBChaine\fP chaine)"
.br
.in -1c
.SH "Description détaillée"
.PP 
\fBEnsemble\fP des chaines\&. 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef \fBEnsemble\fP \fBChaines\fP"
.PP
Chaines est une ensemble de chaine (alias d'un ensemble) \fBVoir également:\fP
.RS 4
\fBEnsemble\fP 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "int \fBchaines_appartient_chaine\fP (\fBChaines\fPchaines, \fBChaine\fPchaine)"Permet de savoir si une chaine appartient a un ensemble de chaines Remarque : une chaine appartient a chaines si une seul des position de la chaine se trouve dans chaines 
.PP
\fBParamètres:\fP
.RS 4
\fIchaines\fP l'ensemble de chaines 
.br
\fIchaine\fP la chaine a verifie 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si chaine appartient a chaines, 0 sinon 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
