.TH "include/couleur.h" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/couleur.h \- 
.PP
La couleur d'un pion\&.  

.SH SYNOPSIS
.br
.PP
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef enum \fBCouleur\fP \fBCouleur\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBCouleur\fP { \fBINDEFINI\fP = -1, \fBVIDE\fP = 0, \fBBLANC\fP = 1, \fBNOIR\fP = 2 }"
.br
.in -1c
.SH "Description détaillée"
.PP 
La couleur d'un pion\&. 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef enum \fBCouleur\fP  \fBCouleur\fP"Permet de représenter la couleur des pionts 
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBCouleur\fP"Permet de représenter la couleur des pionts 
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fIINDEFINI \fP\fP
Cas particulié, non definis 
.TP
\fB\fIVIDE \fP\fP
Permet de représenter une case vide (pas de pion) 
.TP
\fB\fIBLANC \fP\fP
Permet de représenter les pions blancs 
.TP
\fB\fINOIR \fP\fP
Permet de représenter les pions noirs 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
