.TH "src/ensemble_colores.c" 3 "Mardi Février 18 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ensemble_colores.c \- 
.PP
code source qui permet de gérer les ensembles colores  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <position\&.h>\fP
.br
\fC#include <positions\&.h>\fP
.br
\fC#include <ensemble\&.h>\fP
.br
\fC#include <ensemble_colores\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEnsemble_Colores\fP"
.br
.RI "\fIStructure d'un ensemble coloré contient une couleur, et un ensemble de positions\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBEnsemble_Colores\fP \fBcreer_ensemble_colores\fP ()"
.br
.ti -1c
.RI "void \fBensemble_colores_init\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "int \fBensemble_colores_vide\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "\fBCell\fP \fBensemble_colores_tete\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "\fBCell\fP \fBensemble_colores_courant\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "int \fBensemble_colores_suivant\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "\fBPosition\fP * \fBensemble_colores_get_courant\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "int \fBensemble_colores_appartient\fP (\fBEnsemble_Colores\fP E, \fBPosition\fP *element)"
.br
.ti -1c
.RI "\fBEnsemble_Colores\fP \fBensemble_colores_enlever\fP (\fBEnsemble_Colores\fP E, \fBPosition\fP *element)"
.br
.ti -1c
.RI "void \fBensemble_colores_ajouter\fP (\fBEnsemble_Colores\fP E, \fBPosition\fP *element)"
.br
.ti -1c
.RI "void \fBensemble_colores_set_couleur\fP (\fBEnsemble_Colores\fP E, \fBCouleur\fP c)"
.br
.ti -1c
.RI "\fBCouleur\fP \fBensemble_colores_get_couleur\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "void \fBensemble_colores_reset\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "void \fBensemble_colores_set_courant\fP (\fBEnsemble_Colores\fP E, \fBCell\fP c)"
.br
.ti -1c
.RI "\fBCell\fP \fBensemble_colores_get_suivant\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "void \fBensemble_colores_affiche\fP (\fBEnsemble_Colores\fP E)"
.br
.in -1c
.SH "Description détaillée"
.PP 
code source qui permet de gérer les ensembles colores 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013
.RE
.PP
\fBA faire\fP
.RS 4
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "\fBEnsemble_Colores\fP \fBcreer_ensemble_colores\fP ()"Permet de creer un ensemble 
.PP
\fBRenvoie:\fP
.RS 4
un pointeur vers un ensemble 
.RE
.PP

.SS "void \fBensemble_colores_affiche\fP (\fBEnsemble_Colores\fPE)"Permet d'afficher un ensemble colores 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble colores 
.RE
.PP

.SS "void \fBensemble_colores_ajouter\fP (\fBEnsemble_Colores\fPE, \fBPosition\fP *element)"Permet d'ajouter un élément dans un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élément à ajouter 
.RE
.PP

.SS "int \fBensemble_colores_appartient\fP (\fBEnsemble_Colores\fPE, \fBPosition\fP *element)"Permet de vérifier qu'un élément appartiennent à un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élément 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si il appartient, 0 sinon 
.RE
.PP
\fBA faire\fP
.RS 4
il ne devrait pas y avoir de cast\&.\&.\&. on attend les fonctions pour position_get_x, etc\&.\&.\&. 
.RE
.PP

.SS "\fBCell\fP \fBensemble_colores_courant\fP (\fBEnsemble_Colores\fPE)"Permet de positionner le pointeur sur un des éléments de l'ensemble 
.PP
\fBRenvoie:\fP
.RS 4
le pointeur sur l'élément courant 
.RE
.PP

.SS "\fBEnsemble_Colores\fP \fBensemble_colores_enlever\fP (\fBEnsemble_Colores\fPE, \fBPosition\fP *element)"Permet de supprimer un élément dans l'ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élement à supprimer 
.RE
.PP
\fBRenvoie:\fP
.RS 4
E pointeur vers le nouvel ensemble privé de l'élément supprimé 
.RE
.PP

.SS "\fBCouleur\fP \fBensemble_colores_get_couleur\fP (\fBEnsemble_Colores\fPE)"Permet de récupérer la couleur de l'ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP
\fBRenvoie:\fP
.RS 4
La couleur 
.RE
.PP

.SS "\fBPosition\fP* \fBensemble_colores_get_courant\fP (\fBEnsemble_Colores\fPE)"Permet de récupérer la position courrante 
.PP
\fBParamètres:\fP
.RS 4
\fIl'ensemble\fP E 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un pointeur sur la position courante 
.RE
.PP

.SS "\fBCell\fP \fBensemble_colores_get_suivant\fP (\fBEnsemble_Colores\fPE)"Permet de récupérer la cellule suivante d'un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP
\fBRenvoie:\fP
.RS 4
la cellule suivante 
.RE
.PP

.SS "void \fBensemble_colores_init\fP (\fBEnsemble_Colores\fPE)"Permet d'initialiser un ensemble coloré 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensenble coloré 
.RE
.PP

.SS "void \fBensemble_colores_reset\fP (\fBEnsemble_Colores\fPE)"Permet de remettre le pointeur courant sur la tete de l'ensemble colores 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP

.SS "void \fBensemble_colores_set_couleur\fP (\fBEnsemble_Colores\fPE, \fBCouleur\fPc)"Permet de modifier la couleur de l'ensemble colores 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.br
\fIc\fP la couleur 
.RE
.PP

.SS "void \fBensemble_colores_set_courant\fP (\fBEnsemble_Colores\fPE, \fBCell\fPc)"Permet de pointer le courant sur une autre cellule 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.br
\fIc\fP la cellule 
.RE
.PP

.SS "int \fBensemble_colores_suivant\fP (\fBEnsemble_Colores\fPE)"Permet de dire s'il y a un élément suivant ou non 
.PP
\fBRenvoie:\fP
.RS 4
1 ou 0 
.RE
.PP

.SS "\fBCell\fP \fBensemble_colores_tete\fP (\fBEnsemble_Colores\fPE)"Permet de positionner le pointeur tête sur le debut de mon ensemble 
.PP
\fBRenvoie:\fP
.RS 4
le pointeur de la tete de l'ensemble 
.RE
.PP

.SS "int \fBensemble_colores_vide\fP (\fBEnsemble_Colores\fPE)"Permet de vérifier si un ensemble est vide 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si il l'est 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
