.TH "include/ensemble.h" 3 "Mercredi Février 12 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ensemble.h \- 
.PP
structures cell et \fBEnsemble\fP permettant la manipulation d'ensembles  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCell\fP"
.br
.ti -1c
.RI "struct \fBEnsemble\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBCell\fP \fBCell\fP"
.br
.ti -1c
.RI "typedef struct \fBEnsemble\fP \fBEnsemble\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBensemble_init\fP (\fBEnsemble\fP *E)"
.br
.ti -1c
.RI "\fBEnsemble\fP * \fBcreer_ensemble\fP ()"
.br
.ti -1c
.RI "int \fBensemble_vide\fP (\fBEnsemble\fP *E)"
.br
.ti -1c
.RI "int \fBensemble_appartient\fP (\fBEnsemble\fP *E, void *element)"
.br
.ti -1c
.RI "void \fBensemble_ajouter\fP (\fBEnsemble\fP *E, void *element)"
.br
.ti -1c
.RI "\fBEnsemble\fP * \fBensemble_enlever\fP (\fBEnsemble\fP *E, void *element)"
.br
.ti -1c
.RI "\fBCell\fP * \fBensemble_tete\fP (\fBEnsemble\fP *E)"
.br
.ti -1c
.RI "\fBCell\fP * \fBensemble_courant\fP (\fBEnsemble\fP *E)"
.br
.ti -1c
.RI "int \fBensemble_suivant\fP (\fBEnsemble\fP *E)"
.br
.ti -1c
.RI "\fBEnsemble\fP * \fBensemble_concatene\fP (\fBEnsemble\fP *e1, \fBEnsemble\fP *e2)"
.br
.in -1c
.SH "Description détaillée"
.PP 
structures cell et \fBEnsemble\fP permettant la manipulation d'ensembles 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBCell\fP \fBCell\fP"
.SS "typedef struct \fBEnsemble\fP \fBEnsemble\fP"
.SH "Documentation des fonctions"
.PP 
.SS "\fBEnsemble\fP* \fBcreer_ensemble\fP ()"Permet de creer un ensemble 
.PP
\fBRenvoie:\fP
.RS 4
un pointeur vers un ensemble 
.RE
.PP

.SS "void \fBensemble_ajouter\fP (\fBEnsemble\fP *E, void *element)"Permet d'ajouter un élément dans un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élément à ajouter 
.RE
.PP

.SS "int \fBensemble_appartient\fP (\fBEnsemble\fP *E, void *element)"Permet de vérifier qu'un élément appartiennent à un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élément 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si il appartient, 0 sinon 
.RE
.PP

.SS "\fBEnsemble\fP* \fBensemble_concatene\fP (\fBEnsemble\fP *e1, \fBEnsemble\fP *e2)"Përmet de concatener deux ensembles 
.PP
\fBParamètres:\fP
.RS 4
\fIe1\fP l'ensemble e1 ajouter en 'tête' 
.br
\fIe2\fP l'ensemble e2 ajouter en bout de e1 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un nouvel ensemble 
.RE
.PP

.SS "\fBCell\fP* \fBensemble_courant\fP (\fBEnsemble\fP *E)"Permet de positionner le pointeur sur un des éléments de l'ensemble 
.PP
\fBRenvoie:\fP
.RS 4
le pointeur sur l'élément courant 
.RE
.PP

.SS "\fBEnsemble\fP* \fBensemble_enlever\fP (\fBEnsemble\fP *E, void *element)"Permet de supprimer un élément dans l'ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIelement\fP l'élement à supprimer 
.RE
.PP
\fBRenvoie:\fP
.RS 4
E pointeur vers le nouvel ensemble privé de l'élément supprimé 
.RE
.PP

.SS "void \fBensemble_init\fP (\fBEnsemble\fP *E)"Permet d'initialiser un ensemble 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP

.SS "int \fBensemble_suivant\fP (\fBEnsemble\fP *E)"Permet de dire s'il y a un élément suivant ou non 
.PP
\fBRenvoie:\fP
.RS 4
1 ou 0 
.RE
.PP

.SS "\fBCell\fP* \fBensemble_tete\fP (\fBEnsemble\fP *E)"Permet de positionner le pointeur tête sur le debut de mon ensemble 
.PP
\fBRenvoie:\fP
.RS 4
le pointeur de la tete de l'ensemble 
.RE
.PP

.SS "int \fBensemble_vide\fP (\fBEnsemble\fP *E)"Permet de vérifier si un ensemble est vide 
.PP
\fBParamètres:\fP
.RS 4
\fIE\fP l'ensemble 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si il l'estsinon 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
