.TH "Ensemble_Colores" 3 "Mardi Février 18 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ensemble_Colores \- 
.PP
Structure d'un ensemble coloré contient une couleur, et un ensemble de positions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBCouleur\fP \fBc\fP"
.br
.ti -1c
.RI "\fBPositions\fP \fBp\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'un ensemble coloré contient une couleur, et un ensemble de positions\&. 
.SH "Documentation des données membres"
.PP 
.SS "\fBCouleur\fP \fBEnsemble_Colores::c\fP"
.SS "\fBPositions\fP \fBEnsemble_Colores::p\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
