.TH "src/go.c" 3 "Mercredi Février 12 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/go.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <matrice\&.h>\fP
.br
\fC#include <partie\&.h>\fP
.br
\fC#include <plateau\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int \fBmain\fP ()"
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
