.TH "src/libertes.c" 3 "Jeudi Février 20 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libertes.c \- 
.PP
code source qui permet de gérer les libertés  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <matrice\&.h>\fP
.br
\fC#include <ensemble\&.h>\fP
.br
\fC#include <ensemble_colores\&.h>\fP
.br
\fC#include <libertes\&.h>\fP
.br
\fC#include <position\&.h>\fP
.br
\fC#include <positions\&.h>\fP
.br
\fC#include <plateau\&.h>\fP
.br
\fC#include <chaine\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBLibertes\fP \fBdetermineLiberte\fP (\fBPlateau\fP plateau, \fBChaine\fP chaine)"
.br
.in -1c
.SH "Description détaillée"
.PP 
code source qui permet de gérer les libertés 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <yasmine.elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "\fBLibertes\fP \fBdetermineLiberte\fP (\fBPlateau\fPplateau, \fBChaine\fPchaine)"Permet de determiner les libertes d'une chaine 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau 
.br
\fIchaine\fP la chaine contenant un ensemble de position 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un ensemble de positions qui represente les libertes 
.RE
.PP
\fBA faire\fP
.RS 4
optimisation en utilisant deplacer_\&.\&.\&.() mais peut poser problème car deux appels dans la condition\&.\&.\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
