.TH "Matrice" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrice \- 
.PP
Structure d'une matrice qui contient les données de cette matrice, le nombre de ligne et le nombre de colonne\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrice\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int ** \fBdonnees\fP"
.br
.ti -1c
.RI "int \fBnbligne\fP"
.br
.ti -1c
.RI "int \fBnbcolonne\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'une matrice qui contient les données de cette matrice, le nombre de ligne et le nombre de colonne\&. 
.SH "Documentation des données membres"
.PP 
.SS "int** \fBMatrice::donnees\fP"Les tableau des données 
.SS "int \fBMatrice::nbcolonne\fP"Le nombre de colonnes 
.SS "int \fBMatrice::nbligne\fP"Le nombre de lignes 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
