.TH "Partie" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Partie \- 
.PP
Structure d'une partie qui comporte les noms des joueurs, la couleur que choisit chaque joueur et le plateau du jeu\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <partie\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBjoueur1\fP [20]"
.br
.ti -1c
.RI "char \fBjoueur2\fP [20]"
.br
.ti -1c
.RI "\fBCouleur\fP \fBjoueur\fP"
.br
.ti -1c
.RI "\fBPlateau\fP \fBplateau\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure d'une partie qui comporte les noms des joueurs, la couleur que choisit chaque joueur et le plateau du jeu\&. 
.SH "Documentation des données membres"
.PP 
.SS "\fBCouleur\fP \fBPartie::joueur\fP"
.SS "char \fBPartie::joueur1\fP[20]"
.SS "char \fBPartie::joueur2\fP[20]"
.SS "\fBPlateau\fP \fBPartie::plateau\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
