.TH "include/plateau.h" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/plateau.h \- 
.PP
Contient la position de l'ensemble des pions sur la grille\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <matrice\&.h>\fP
.br
\fC#include <chaine\&.h>\fP
.br
\fC#include <position\&.h>\fP
.br
\fC#include <pion\&.h>\fP
.br
\fC#include <chaines\&.h>\fP
.br
\fC#include <territoire\&.h>\fP
.br

.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBMatrice\fP \fBPlateau\fP"
.br
.RI "\fIStructure d'un plateau de jeu\&. Plateau est un alias du type \fBMatrice\fP\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBplateau_afficher\fP (\fBPlateau\fP p)"
.br
.ti -1c
.RI "\fBPlateau\fP \fBcreer_plateau\fP (int taille)"
.br
.ti -1c
.RI "int \fBest_un_pion\fP (\fBCouleur\fP c)"
.br
.ti -1c
.RI "int \fBest_un_pion_plateau\fP (\fBPlateau\fP plateau, \fBPosition\fP pos)"
.br
.ti -1c
.RI "\fBCouleur\fP \fBplateau_get\fP (\fBPlateau\fP m, int x, int y)"
.br
.ti -1c
.RI "\fBCouleur\fP \fBplateau_get_pos\fP (\fBPlateau\fP p, \fBPosition\fP pos)"
.br
.ti -1c
.RI "void \fBplateau_set\fP (\fBPlateau\fP m, int i, int j, \fBCouleur\fP c)"
.br
.ti -1c
.RI "\fBChaine\fP \fBplateau_determiner_chaine\fP (\fBPlateau\fP plateau, \fBPosition\fP pos)"
.br
.ti -1c
.RI "void \fBplateau_realiser_capture\fP (\fBPlateau\fP plateau, \fBChaine\fP chaine)"
.br
.ti -1c
.RI "int \fBplateau_est_identique\fP (\fBPlateau\fP plateau, \fBPlateau\fP ancienPlateau)"
.br
.ti -1c
.RI "int \fBplateau_copie\fP (\fBPlateau\fP from, \fBPlateau\fP to)"
.br
.ti -1c
.RI "\fBChaines\fP \fBplateau_entoure_un_territoire\fP (\fBTerritoire\fP leTerritoire, \fBPlateau\fP plateau)"
.br
.ti -1c
.RI "int \fBplateau_sauvegarde\fP (\fBPlateau\fP plateau, FILE *fichier)"
.br
.ti -1c
.RI "int \fBplateau_position_appartient\fP (\fBPlateau\fP plateau, \fBPosition\fP position)"
.br
.ti -1c
.RI "\fBPlateau\fP \fBplateau_chargement\fP (FILE *fichier)"
.br
.ti -1c
.RI "\fBChaines\fP \fBcaptureChaines\fP (\fBPlateau\fP plateau, \fBPion\fP pion, int *valide)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Contient la position de l'ensemble des pions sur la grille\&. 

ENSICAEN 6 Boulevard Marechal Juin F-14050 Caen Cedex
.PP
This file is owned by ENSICAEN students\&. No portion of this document may be reproduced, copied or revised without written premission of the authors 
.PP
\fBAuteur:\fP
.RS 4
ELHIMDI Yasmine <elhimdi@ecole.ensicaen.fr> 
.PP
PARMENTIER Laurent <parmentier@ecole.ensicaen.fr, laubosslink@society-lbl.com> 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
03-02-2013 
.RE
.PP

.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBMatrice\fP \fBPlateau\fP"
.PP
Structure d'un plateau de jeu\&. Plateau est un alias du type \fBMatrice\fP\&. 
.SH "Documentation des fonctions"
.PP 
.SS "\fBChaines\fP \fBcaptureChaines\fP (\fBPlateau\fPplateau, \fBPion\fPpion, int *valide)"En fonction de la position du pion et de sa couleur, retourne les chaines captures\&. Si aucune chaine n'est capturé par la pose du pion, alors la valeur NULL est retournée\&. L'entier (référencé par) valide est égal à zéro si le fait de placer le pion en cette position conduit à construire une chaine sans liberté de la couleur du pion (sauf si ce coup produit la capture d'au moins une chaine adverse)\&. Dans le cas contraire l'entier référencé par valide est égale à 1
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP Le plateau 
.br
\fIpion\fP le pion 
.br
\fIvalide\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un ensemble de chaine 
.RE
.PP

.SS "\fBPlateau\fP \fBcreer_plateau\fP (inttaille)"Permet de creer un plateau [taille x taille] 
.PP
\fBParamètres:\fP
.RS 4
\fItaille\fP 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un plateau 
.RE
.PP

.SS "int \fBest_un_pion\fP (\fBCouleur\fPc)"Permet de savoir si la couleur est un pion 
.PP
\fBParamètres:\fP
.RS 4
\fIc\fP la couleur 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si c'est un pion, 0 sinon 
.RE
.PP

.SS "int \fBest_un_pion_plateau\fP (\fBPlateau\fPplateau, \fBPosition\fPpos)"Permet de savoir si c'est un pion du plateau 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP Le plateau 
.br
\fIpos\fP La position d'un plateau 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si le pion est dans le plateau, 0 sinon 
.RE
.PP

.SS "void \fBplateau_afficher\fP (\fBPlateau\fPp)"Permet d'afficher un plateau dans la console 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP le plateau 
.RE
.PP

.SS "\fBPlateau\fP \fBplateau_chargement\fP (FILE *fichier)"Permet de charger un plateau a partir d'un fichier 
.PP
\fBParamètres:\fP
.RS 4
\fIfichier\fP le fichier qui contient le plateau 
.RE
.PP
\fBRenvoie:\fP
.RS 4
un plateau 
.RE
.PP

.SS "int \fBplateau_copie\fP (\fBPlateau\fPfrom, \fBPlateau\fPto)"Copie un plateau, les deux tableaux sont supposes deja alloues 
.PP
\fBParamètres:\fP
.RS 4
\fIfrom\fP le plateau source 
.br
\fIto\fP le plateau destination 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si la copie a fonctionnee, 0 sinon 
.RE
.PP

.SS "\fBChaine\fP \fBplateau_determiner_chaine\fP (\fBPlateau\fPplateau, \fBPosition\fPpos)"Produit la chaine a laquelle appartient le pion, a la position pos sur le plateau\&. Si il n'y a pas de pion, sur cette case alors le resultat est NULL 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau 
.br
\fIpos\fP la position du pion 
.RE
.PP
\fBRenvoie:\fP
.RS 4
NULL si il n'y a pas de pion, une chaine sinon 
.RE
.PP

.SS "\fBChaines\fP \fBplateau_entoure_un_territoire\fP (\fBTerritoire\fPleTerritoire, \fBPlateau\fPplateau)"Determine la ou les chaines entourant un territoire 
.PP
\fBParamètres:\fP
.RS 4
\fIleTerritoire\fP le territoire 
.br
\fIplateau\fP le plateau 
.RE
.PP
\fBRenvoie:\fP
.RS 4
une ou plusieurs chaines 
.RE
.PP

.SS "int \fBplateau_est_identique\fP (\fBPlateau\fPplateau, \fBPlateau\fPancienPlateau)"indique sur l'organisation du plateau est identique a une precedente organisation de plateau\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau actuel 
.br
\fIancienPlateau\fP l'ancien plateau 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si identique, 0 sinon 
.RE
.PP

.SS "\fBCouleur\fP \fBplateau_get\fP (\fBPlateau\fPm, intx, inty)"Permet de recuperer un pion sur une position 
.PP
\fBParamètres:\fP
.RS 4
\fIm\fP la matrice 
.br
\fIx\fP l'abscisse 
.br
\fIy\fP l'ordonnee 
.RE
.PP
\fBRenvoie:\fP
.RS 4
La couleur du pion 
.RE
.PP

.SS "\fBCouleur\fP \fBplateau_get_pos\fP (\fBPlateau\fPp, \fBPosition\fPpos)"Permet de recuperer un pion sur une position 
.PP
\fBParamètres:\fP
.RS 4
\fIp\fP le plateau 
.br
\fIpos\fP la position 
.RE
.PP
\fBRenvoie:\fP
.RS 4
La couleur du pion 
.RE
.PP

.SS "int \fBplateau_position_appartient\fP (\fBPlateau\fPplateau, \fBPosition\fPposition)"Permet de savoir si une position est sur plateau 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau 
.br
\fIposition\fP la position à vérifier 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si elle appartient au plateau, 0 sinon 
.RE
.PP

.SS "void \fBplateau_realiser_capture\fP (\fBPlateau\fPplateau, \fBChaine\fPchaine)"Realise la capture des pions correspondant a la chaine en les enlevant du plateau 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau 
.br
\fIchaine\fP une chaine 
.RE
.PP

.SS "int \fBplateau_sauvegarde\fP (\fBPlateau\fPplateau, FILE *fichier)"Permet de sauvegarde un plateau dans un fichier 
.PP
\fBParamètres:\fP
.RS 4
\fIplateau\fP le plateau 
.br
\fIfichier\fP le fichier dans lequel on sauvegarde le plateau 
.RE
.PP
\fBRenvoie:\fP
.RS 4
1 si tout s'est bien passé, 0 sinon 
.RE
.PP

.SS "void \fBplateau_set\fP (\fBPlateau\fPm, inti, intj, \fBCouleur\fPc)"Permet de mettre un pion sur le plateau 
.PP
\fBParamètres:\fP
.RS 4
\fIm\fP la matrice 
.br
\fIi\fP l'abscisse 
.br
\fIj\fP l'ordonnee 
.br
\fIc\fP la couleur du pion 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
