.TH "include/positions.h" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/positions.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <position\&.h>\fP
.br
\fC#include <ensemble_positions\&.h>\fP
.br

.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef \fBEnsemble_Positions\fP \fBPositions\fP"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef \fBEnsemble_Positions\fP \fBPositions\fP"
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
