.TH "Position" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <position\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Permet de définir une position 2D 
.SH "Documentation des données membres"
.PP 
.SS "int \fBPosition::x\fP"
.SS "int \fBPosition::y\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
