.TH "test/test_capture_chaines.c" 3 "Mercredi Février 19 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_capture_chaines.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <plateau\&.h>\fP
.br
\fC#include <pion\&.h>\fP
.br
\fC#include <position\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBnbr_elmt\fP (\fBChaines\fP E)"
.br
.ti -1c
.RI "void \fBaffiche_positions\fP (\fBEnsemble_Colores\fP E)"
.br
.ti -1c
.RI "void \fBaffiche_captures\fP (\fBChaines\fP chaines)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void \fBaffiche_captures\fP (\fBChaines\fPchaines)"
.SS "void \fBaffiche_positions\fP (\fBEnsemble_Colores\fPE)"
.SS "int \fBmain\fP ()"
.SS "int \fBnbr_elmt\fP (\fBChaines\fPE)"
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
