.TH "test/test_ensemble_colores.c" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/test_ensemble_colores.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <position\&.h>\fP
.br
\fC#include <positions\&.h>\fP
.br
\fC#include <ensemble_colores\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBafficherEnsembleColores\fP (\fBEnsemble_Colores\fP *E)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void \fBafficherEnsembleColores\fP (\fBEnsemble_Colores\fP *E)"
.SS "int \fBmain\fP ()"
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Jeu du GO à partir du code source\&.
