.TH "todo" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Liste des choses à faire 
.IP "\fBMembre \fBdetermineLiberte\fP (Plateau plateau, Chaine chaine)\fP" 1c
utiliser haut,bas,gauche,droite  
.IP "\fBFichier \fBensemble_positions\&.h\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBMembre \fBMatrice\fP \fP" 1c
description de la structure 
.PP

