.TH "todo" 3 "Dimanche Février 16 2014" "Jeu du GO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Liste des choses à faire 
.IP "\fBMembre \fBdetermineLiberte\fP (Plateau plateau, Chaine chaine)\fP" 1c
réfléchir sur le struct dans le \&.c, et conséquence sur chaine 
.PP
utiliser haut,bas,gauche,droite  
.IP "\fBFichier \fBensemble\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBFichier \fBensemble_colores\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBMembre \fBensemble_courant\fP (\fBEnsemble\fP *E)\fP" 1c
get_  
.IP "\fBFichier \fBensemble_positions\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBMembre \fBensemble_tete\fP (\fBEnsemble\fP *E)\fP" 1c
get_  
.IP "\fBFichier \fBlibertes\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBFichier \fBposition\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBFichier \fBpositions\&.h\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBFichier \fBtest_ensemble\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position  
.IP "\fBFichier \fBtest_matrice\&.c\fP \fP" 1c
revoir la doc / remplacer Ensemble_Positions par Ensemble_Position 
.PP

